providers:
  kubernetesGateway:
    enabled: true
gateway:
  enabled: true
  listeners:
    websecure:
      hostname: "*.mi6.com"
      port: 8443
      protocol: HTTPS
      certificateRefs:
        - name: wildcard-mi6-tls
